INCLUDE MACROS.ASM
    .8086
    .MODEL SMALL
    .STACK 256    


DATA SEGMENT
    MSG1 DB 0AH,0DH,'START(Y,N):$'
    MSG2 DB 0AH,0DH,'ERROR$'
DATA ENDS

CODE SEGMENT
    ASSUME CS : CODE, DS : DATA

MAIN PROC FAR
    MOV AX, DATA
    MOV DS, AX   
 START:
    PRINT_STR MSG1	;PRINT STARTING MESSAGE
    CALL HEX_KEYB       ;INPUT FIRST DIGIT
    CMP AL,'Y'		;if Y start 
    JZ INPUT2
    CMP AL,'N'		;if N end
    JZ ENDING
    JMP START		;ELSE AGAIN
INPUT2:
    MOV AX,0H
    CALL HEX_KEYB	;INPUT FIRST DIGIT   
    MOV BH,AL
    CMP AL,'Y'
    JE INPUT2		;IF Y START ALL OVER
    CMP AL,'N'
    JE ENDING		; IF N END
    CALL HEX_KEYB       ;INPUT SECOND DIGIT
    CMP AL,'Y'
    JE INPUT2
    CMP AL,'N'
    JE ENDING
    MOV BL,AL
    ROL BL,4
    CALL HEX_KEYB       ;INPUT THIRD DIGIT
    CMP AL,'Y'
    JE INPUT2
    CMP AL,'N'
    JE START
    ADD BL,AL
    CMP BX,500D		;IF <500 (ASSUMING>0) CASE 1
    JNA FIRST_CASE
    CMP BX,700D		;IF (500<)x<700 (ASSUMING>0) CASE 2
    JNA SECOND_CASE
    CMP BX,1000D	;IF (700<)x<1000 (ASSUMING>0) CASE 3
    JNA THIRD_CASE
    PRINT_STR MSG2
    NEW_LINE
    JMP START
FIRST_CASE:
    MOV AX,BX
    MOV DX,50D
    DIV DX              ;FIND V IN FIRST CASE=T*10/500
    JMP ENDING
SECOND_CASE:
    MOV AX,BX
    SUB AX,500D
    MOV DL,80H
    MUL DL
    MOV DX,2000D
    DIV DL
    ADD AX,01H          ;FIND V IN SECOND CASE=1+0,8(T-500)*10/200
    JMP ENDING
THIRD_CASE:
    MOV AX,BX
    SUB AX,700D
    MOV DL,20H
    MUL DL
    MOV DX,300D
    DIV DL
    ADD AX,18D          ;FIND V IN THIRD CASE=1+0,2(T-700)*10/300
    MOV DL,10D
    DIV DL
    JMP ENDING

OUTPUT:
    MOV DX,4095D	;APPLY A/C EQUATION (=4095*V/2)
    MUL DL
    MOV DL,2D
    DIV DL
    MOV BX,AX
    MOV DX,1000D
    DIV DL
    PRINT_DEC		;PRINT D3,D2
    MUL DL
    MOV CX,AX
    MOV DL,10D
    MOV AX,BX
    SUB AX,CX
    MOV CX,AX
    DIV DL
    PRINT_DEC		;PRINT D1,D0
    MOV CX,AX
    PRINT ','		;PRINT ,
    SUB BX,CX
    MOV AX,BX
    PRINT_DEC		;PRINT D(-1)
    JMP START
ENDING: 
    EXIT
    MAIN ENDP
   

HEX_KEYB PROC NEAR    
    PUSH DX
IGNORE:
    READ
    CMP AL,'Y'
    JE ADDR2 
    CMP AL,'N'
    JE ADDR2 
    CMP AL,30H 
    JL IGNORE 
    CMP AL,39H
    JG ADDR1                  
    SUB AL,30H  
    JMP ADDR2              
ADDR1:  
    CMP AL,'A'
    JL IGNORE         
    CMP AL,'F'
    JG IGNORE 
    SUB AL,37H             
ADDR2:              
    POP DX 
    RET 
HEX_KEYB ENDP 
